# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b4bb9eceec6a1ad246c93491c6c6752"
name = "besync v2"
application_url = "https://besyncv2-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://example.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://example.com/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_fulfillments,write_fulfillments,read_orders,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://besyncv2-production.up.railway.app/auth/callback",
  "https://besyncv2-production.up.railway.app/auth/session-token",
  "https://besyncv2-production.up.railway.app/api/auth/callback",
  "https://besyncv2-production.up.railway.app/api/auth/session-token"
]
